# Adapted from https://github.com/PyMySQL/PyMySQL/blob/master/.travis.yml
dist: xenial
language: python
cache: pip

services:
  - docker

matrix:
  include:
    - env:
        - DB=mariadb:5.5
      python: "3.5"
    - env:
        - DB=mariadb:10.0
      python: "3.6"
    - env:
        - DB=mariadb:10.2
      python: "2.7"
    - env:
        - DB=mariadb:10.3
      python: "3.7"
    - env:
        - DB=mariadb:10.3
      python: "3.7-dev"
    - env:
        - DB=mysql:5.5
      python: "3.5"
    - env:
        - DB=mysql:5.6
      python: "3.6"
    - env:
        - DB=mysql:5.7
      python: "3.7"
    - env:
        - DB=mysql:8.0
      python: "3.7"
    - env:
        - DB=mysql:8.0
      python: "3.7-dev"
    - env:
        - DB=mysql:8.0
      python: "2.7"

install:
  - pip install -q -r requirements-test.txt
  - pip install -q -e .

before_script:
  - bash ./.travis/initdb.sh
  - python -VV
  - rm -f ~/.my.cnf

script:
  - pytest --cov=sqlite3_to_mysql --mysql-user=tester --mysql-password=testpass --mysql-database=test_db --mysql-host=localhost --mysql-port=3306 --no-docker

env:
  - CODECOV_TOKEN="1ec34933-5c4e-491d-9c8e-1af588cf2f00"

after_success:
  - codecov