dist: xenial
language: python
cache: pip

services:
  - docker

matrix:
  include:
    - env:
        - DB=mariadb:5.5
      python: "3.5"
    - env:
        - DB=mariadb:10.0
      python: "3.6"
    - env:
        - DB=mariadb:10.3
      python: "3.7"
    - env:
        - DB=mysql:5.5
      python: "3.5"
    - env:
        - DB=mysql:5.6
      python: "3.6"
    - env:
        - DB=mysql:5.7
      python: "3.7"
    - env:
        - DB=mysql:8.0
        - TEST_AUTH=yes
      python: "3.7"

install:
  - pip install -r requirements-test.txt

before_script:
  - ./.travis/initializedb.sh
  - python -VV
  - rm -f ~/.my.cnf
  - export COVERALLS_PARALLEL=true

script:
  - pytest --cov=src --mysql-user=tester --mysql-password=testpass --mysql-database=test_db --mysql-host=localhost --mysql-port=3306 --no-docker